---
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

master_task:
  skip: "!changesInclude('.cirrus.yml', 'scripts/**')"

  environment:
    VERSION: master
    BUILD_TYPE: disk

  install_script:
    - apt-get update
    - apt-get install python3-pip
    - pip install -r requirements.txt
    - bash scripts/install.sh
    - echo $CIRRUS_BRANCH

  submodules_script:
    - git submodule init
    - git submodule update

  build_script:
    - bash scripts/build.sh
    - echo $CIRRUS_BRANCH

  deploy_task:
    only_if: $CIRRUS_BRANCH == 'master'
    skript: bash scripts/push.sh

victoria_task:
  skip: "!changesInclude('.cirrus.yml', 'scripts/**')"

  environment:
    VERSION: victoria
    BUILD_TYPE: disk

  install_script:
    - apt-get update
    - apt-get install python3-pip
    - pip install -r requirements.txt
    - bash scripts/install.sh
    - echo $CIRRUS_BRANCH

  submodules_script:
    - git submodule init
    - git submodule update

  build_script:
    - bash scripts/build.sh
    - echo $CIRRUS_BRANCH

  deploy_task:
    only_if: $CIRRUS_BRANCH == 'master'
    skript: bash scripts/push.sh

wallaby_task:
  skip: "!changesInclude('.cirrus.yml', 'scripts/**')"

  environment:
    VERSION: wallaby
    BUILD_TYPE: disk

  install_script:
    - apt-get update
    - apt-get install python3-pip
    - pip install -r requirements.txt
    - bash scripts/install.sh
    - echo $CIRRUS_BRANCH

  submodules_script:
    - git submodule init
    - git submodule update

  build_script:
    - bash scripts/build.sh
    - echo $CIRRUS_BRANCH

  deploy_task:
    only_if: $CIRRUS_BRANCH == 'master'
    skript: bash scripts/push.sh
