---
dist: bionic
language: python

install:
  - pip install -r requirements.txt
  - bash scripts/install.sh

env:
  matrix:
    - VERSION=master BUILD_TYPE=disk
    - VERSION=master BUILD_TYPE=container
    - VERSION=rocky BUILD_TYPE=disk
    - VERSION=rocky BUILD_TYPE=container
    - VERSION=train BUILD_TYPE=disk
    - VERSION=train BUILD_TYPE=container
    - VERSION=stein BUILD_TYPE=disk
    - VERSION=stein BUILD_TYPE=container
    - VERSION=ussuri BUILD_TYPE=disk
    - VERSION=ussuri BUILD_TYPE=container
    - VERSION=victoria BUILD_TYPE=disk
    - VERSION=victoria BUILD_TYPE=container

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
