---
- secret:
    name: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
    data:
      ACCESS_KEY: !encrypted/pkcs1-oaep
        - Ycj1OmCXNeajEdcY9uXxi7LEqmTriNjUSwl4VLz9BD3DE3rVv6IfHte2cxcUVjLhrpOPm
          bgHue6Zta0cPhh2RSVwCOIi4ZwycQchCa+1b14qY+S9nG26loR+ZQBi3L4LWeAvSJfJcW
          LLP9tDYTwbJ4nuhOexX4+kXOol9Xu6ttm7AJBhG8tr/bjCpFcUhuMIYIPzrcdKs5y4znf
          C/6XFqnlWxcCcbEhGYRvNr6fyLAS6bb31TtR2EnrCbjVAMhlNcLzVz/qkcwB+wqlLhOzC
          0Gg116s/DBIVVEtsETp8gJFAGzJGvY8hieuSHVR+c0BhPbqrqr6mnVSjMnpnMoYIQRB1M
          mo5R/PblIaK3U4T14zROOJnp/9h6pkNmOR/S8hgVyvD4cnwxlT64WuNTZEgo5ygLTdkIj
          H1Fq2YCSI5f2cLkFkv4GQDKwMloY2yIJPvRmBaDadTAvL7rYbtTjN3f9elWXLqLL9/gpH
          yo794k2mwSlwulTMHy4P8cnzdigfwe+fkv4qAvtu0psdFormuF8FXJ+L0aM9JteUa9elO
          DQovTPbeh6V43Ucp9c3y2BWFO3+vH8/yGfybyXkkE1VqKeI+AqXmP8Q6HE0KNmX4EdkvM
          +L5wJm92JXoRIMp2Gm9uFMhb1QZsgBmOYkBErR3woM+2rYUG5WH57D2Z4Lxu/g=
      SECRET_KEY: !encrypted/pkcs1-oaep
        - VHGJjkq6lnW+SZnt4XrIOZmqnvFbQcvKTCRIbeYFE7rITuJojMlPzJH1Rzjr8IBtzSKQC
          y6HQ1DvrH6MCo/uuLSLhLIsdj/VMLsHT6heGGNC3g0VNbIsY6PczN0Ihtn39peRtG0R9/
          8ZZJSNTEqFNl9BU1SXiTgmF0XMiPAQYt5rM97rKXanSf7dYqx0XSijJBLxXw3Lq0ZlIuQ
          4loLbrLQt2am65HCTPSga1gDVyeHYcBVdgb1proFX0KwdxuYILmAG2PbBP0g4cgyHCZfj
          FwmHMcA4XKryMvMPI12BETqnnK8PjpcmM95aFdwUZBGcMohftS/YCsbTGrMf7tLYtLqAR
          s9GArL7sU7MsafMoy5sayFoyHsm7un62n4RZWBwufR8dwIgAF9451oi1VTuQ0/Zi9nAvF
          EehcWtkWfV67bfXIwVoH+PAwdvKN55T1VRPp8CNlseAc+XGhYzZVLAwdPTO7AtzD8kKqB
          Acp4eWzctTF2j29R5G9X5fyA/9t8pvKLcNxiUO0q7OwM3AZamCOzq4IaC7qXMfUqfQpTF
          bFSS4PKpt/wWIz7kLmcEMrsGx7OwNysOOq6yLhKdkhEg9fXnMCzGeVEj51PzdSI3pVlh+
          7NnXRPCtUScz1y2mIphagEIWwHdSpmv+YRL8jCCmPBkTes4xdkX2AqXyye/Sko=

- semaphore:
    name: semaphore-openstack-octavia-amphora-image-publish
    max: 1

- job:
    name: openstack-octavia-amphora-image-build
    nodeset: ubuntu-jammy-large
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: openstack-octavia-amphora-image-build-zed
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: zed
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-antelope
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-bobcat
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-publish-zed
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: zed
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-antelope
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-bobcat
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - openstack-octavia-amphora-image-build-zed
        - openstack-octavia-amphora-image-build-antelope
        - openstack-octavia-amphora-image-build-bobcat
    periodic-daily:
      jobs:
        - openstack-octavia-amphora-image-publish-zed
        - openstack-octavia-amphora-image-publish-antelope
        - openstack-octavia-amphora-image-publish-bobcat
    post:
      jobs:
        - openstack-octavia-amphora-image-publish-zed:
            branches: main
        - openstack-octavia-amphora-image-publish-antelope:
            branches: main
        - openstack-octavia-amphora-image-publish-bobcat:
            branches: main
