---
- secret:
    name: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
    data:
      ACCESS_KEY: !encrypted/pkcs1-oaep
        - k+cbOC0Ghnlc+ysJUkTL0uBjsjd1tQN8ky1ISCtPFnhuUfZajet0A3Uy4h0YpO46NlB/k
          ozMlw/O4gd8s+pUp1zlFZj9CzDb+1vj0shJy+2cTICzJKzCjSlKBBWvrSgdd/YBSXuaY4
          Taw6MttWI3wo4hQzKwNdCESwt3/fQc5lmkkbdOYXpUq7zzIRWygBBm16VNiQFogEq57PL
          Ge3IY/o4a+XkB/kjbURmIu3UYIv8EqwpXOglVHrKuibAd/ZyV0sDUzfX/lk3A+kn5vful
          I1ijp+LU8W7ilGvFQV+Tla2/hrs+dfm+Z8fALLHp5Fppexb06UzmB3b6AovGUEJKqRnNQ
          qaXcTrrbNVlrT53DqiKFL0AJ4++GCPkW/mqkB+iphOXIDUxa7VodusKj8imKYt6OAnhBp
          n4L5VERHc0GWqj4qCn9t7mBdEL09QMWpP/5v5C1UfqlPKWArnkZIf4CrGZxgAJPHIM6YZ
          nL4sJ+AwvcOjb5Uz5If1WswXuU8kdKHdLcLAAZpXcvi6IjlgDjyIk+HhPLq0C/irF4gQI
          2yXdUTB1SiLpJdVCv4wQfzGX3jMKTqZ8b/06a2+jCOhcCG2cZeaPP15HRYHQKBIeoAGxm
          i6OeiuLXc3BzMC/yLcml6nTtpiigthDHykpHDYRdSZ8sNQXuLfJz3naUeR6+/c=
      SECRET_KEY: !encrypted/pkcs1-oaep
        - HBEnHK90cvs0pzr8fg3KNM9B9FDUI48SsWE/YJLJevDninT4sOTNJamCPLNpvKyUdvdPi
          chBL1PL0FICc0tZ9CrdFuIw0Q1SzUdzp6rA6mRUlFe5TwWgLdCOm2c+JlKpRQyzAEbK8x
          kdgscKY3j2bno/aK3ONHBx0bdelIBiky/wn7nvMG8xOM4lmz9Z8mgWXGicYn+caiQleEI
          +SMgj/S1yILusDssCvgzxlGSiehv3q13PR1gJ3a175s/XuPBtRIe180LG1boVH39I/v6m
          YEgdSJnLgKqGItPXWP9AGnDy4zlBn6cBrve6K8qZnxSX33Yi/83SJA93RPvwqF2fiy5gN
          mHxupvxG2VPx/IZzlffWfRNmxDHSTH1XqVguSxxtC2rWYYOUPdRV9bOu15qGwl2dJ7HZB
          H/X9+X0JRlWYPIi5y7NZPAlHC4z/iaE8CauHY0MpqUMBPznu3XNpk+znMakY3gHOy/R+X
          GYW5igqM+4H1PBVaujec9W0Krkra4XseYar/uwkRgF5LkXHKlw4Ti3PgUyjl1H4w5CEae
          cbdGn/D92S/P6QyWr3gxUYtzX4CJr4KTyU2TpEJqwZAULdXWPimUwz3uznrPK68kEPu82
          Ro1abAAcIIm2sXtM+kYjqDYnag7459xz/iyA0cdDAZGTI7EVTZEXvpRd5D+kYY=

- semaphore:
    name: semaphore-openstack-octavia-amphora-image-publish
    max: 1

- job:
    name: openstack-octavia-amphora-image-cleanup
    run: playbooks/cleanup.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-build
    nodeset: ubuntu-jammy-large
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: openstack-octavia-amphora-image-build-2023.1
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2023.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2024.1
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2024.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2025.1
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2025.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-publish-2023.1
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2023.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2024.1
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2024.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2025.1
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2025.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - openstack-octavia-amphora-image-build-2023.1
        - openstack-octavia-amphora-image-build-2023.2
        - openstack-octavia-amphora-image-build-2024.1
        - openstack-octavia-amphora-image-build-2024.2
        - openstack-octavia-amphora-image-build-2025.1
        - openstack-octavia-amphora-image-build-2025.2
    periodic-daily:
      jobs:
        - openstack-octavia-amphora-image-cleanup
        - openstack-octavia-amphora-image-publish-2023.1
        - openstack-octavia-amphora-image-publish-2023.2
        - openstack-octavia-amphora-image-publish-2024.1
        - openstack-octavia-amphora-image-publish-2024.2
        - openstack-octavia-amphora-image-publish-2025.1
        - openstack-octavia-amphora-image-publish-2025.2
    post:
      jobs:
        - openstack-octavia-amphora-image-cleanup:
            branches: main
        - openstack-octavia-amphora-image-publish-2023.1:
            branches: main
        - openstack-octavia-amphora-image-publish-2023.2:
            branches: main
        - openstack-octavia-amphora-image-publish-2024.1:
            branches: main
        - openstack-octavia-amphora-image-publish-2024.2:
            branches: main
        - openstack-octavia-amphora-image-publish-2025.1:
            branches: main
        - openstack-octavia-amphora-image-publish-2025.2:
            branches: main
