---
- secret:
    name: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
    data:
      ACCESS_KEY: !encrypted/pkcs1-oaep
        - STBVGk7yat2xcRJ5uVltOEIupSfgE0PP2xeNafdFb84S0iXZjsnrREhrv7il1tLrtEY03
          wwyE1fKuaZMpaWwL+teJOo8ZZ7oGgCVWYLPA8G5YwnNulUd43ixOq1nYzjjQrNaAQ1P5n
          /1tlJ5Z3cixurciLv91lnQ5zjP3SiYygTosuFZKiByOtIp72j/EGo69u771CxnqB5QeHS
          +A9u0W2047Fw9XOxzneo7BOhZ/Zzi6cBgKru2Y6nMHweoYSFv8qS7Tnl41kICWAkPzFi2
          MlE4mUKFrTYiHdN5JiKFF74qsHnliU9EVK4GN/7Wf0Pbmd5Amm5r73kKc/7P4C4CeYdwI
          UIKx4HfRoCLTwecxCt/Yf7rDNHF978ey9YC0dHjSdu1oR+vJSpTMDhhNe3yK8Dfuv4Jv7
          My3Z83T/V/52WPbukQ1NZRC0rZQojr5DcrsPa4xfs6WutdBvz611FaNQjrwqoqweVQGnO
          hK0rAsr8mB9WkvmnfVY3RJs8KL9TVyNy8IWqjxO3Yrvj5s6m3nfx/YfvNQbtcJyPZRKie
          it/1uZeW1hT3O8Jl0ngwxcocAGAd4dYTjhQqDEoFIRzyDl0HF95LEHfAtIy+KvbxCYNPc
          g6CbIIYuEr0PwTG/QKyv/nQl0zKf3IQWQbIx8Vl/ngiQPgEBYYMQPonxWv6Z9Q=
      SECRET_KEY: !encrypted/pkcs1-oaep
        - LV6KUhZXZufqSeYGCCrx6hkGuzhbK0sDdagn9kWeUilA51bXZWy5ZPpKVtBEr4QK204D/
          vxB1g1fta1X++XOGLtl7ud4Z6mlwdxZqclog0sHLA90gQoADH55FcXVPTUvLFlkNg0Oxr
          J0Z2h/H5ZxQXSpXCIvmsl4F8fd+EoK7UYYz8Lwe851ZO4VVzb7J5YlhXUGQLGXAAeYvBz
          AXhnB/5y0UtajB0sXOIkpg+xgvAGwJHqJ1+SahNyqs3ZzKR0AG72GH++w8gPYp3ZRDstN
          omdNsjQNjUPXLso08UVC9fTfHeha441UuRJxJrrGYSC1OaRRcrdj3CR5ucRJKAw+pDfiw
          KGyq4ftuMjGITvfRCW80I0ZfJh0EyJYkz849GXtxixwe4D5wAumKGIHAniM3KRfNRyaYN
          OUcCeFo/yAYuu2CJt1hr6Po2PkwdVI/GpNAXeuowdXwGfUxZOR+U0No/5mIjmI8937iap
          6bbiLs635r6libNgHMoZSSvWhS75eTF9dsLettKoIdBwqIOyr/vqddyZ/1tCJ7Hy4KbSz
          tz8aJb2xLfqPWxB9ya0afbOZRS5+brBNAjNbvev6Ey3B78yTfvBwAwlglhrIIiwuMLhJ/
          xYoto3nGklK2hOiUZSHk0cqkxSTmn7MzNlGKDJ8WD0HEr2jzQCO2I3ngGUXOcI=

- semaphore:
    name: semaphore-openstack-octavia-amphora-image-publish
    max: 1

- job:
    name: openstack-octavia-amphora-image-cleanup
    run: playbooks/cleanup.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-build
    nodeset: ubuntu-jammy-large
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: openstack-octavia-amphora-image-build-2024.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2025.1
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2025.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-publish-2024.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2025.1
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2025.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2025.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - openstack-octavia-amphora-image-build-2024.2
        - openstack-octavia-amphora-image-build-2025.1
        - openstack-octavia-amphora-image-build-2025.2
    periodic-daily:
      jobs:
        - openstack-octavia-amphora-image-cleanup
        - openstack-octavia-amphora-image-publish-2024.2
        - openstack-octavia-amphora-image-publish-2025.1
        - openstack-octavia-amphora-image-publish-2025.2
    post:
      jobs:
        - openstack-octavia-amphora-image-cleanup:
            branches: main
        - openstack-octavia-amphora-image-publish-2024.2:
            branches: main
        - openstack-octavia-amphora-image-publish-2025.1:
            branches: main
        - openstack-octavia-amphora-image-publish-2025.2:
            branches: main
