---
- secret:
    name: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
    data:
      ACCESS_KEY: !encrypted/pkcs1-oaep
        - EnnITO+MigDFM7LWAYYdYFMfJUSqGU7sBgqk0ZErsfAcM7uQtIKu21MQIrEyI09bGnOiA
          srZ30Gbi9P5IGvLZIkyQfellV2mqzFUMoc2bPUZs8l6j/2ztCNvTQnfI5y4PL6oKs9tJL
          MfpKQaHeC3Fk+XVOp8UqubmoStb5ljdiYgZz42fAaPIEo2buNG2WgfkJ/2qozZUQkeDdG
          N3N/FSAD30B2QK+IYwEhXQqE/kIoMOMRhS6dzaQQpXQ+3JxhrjRfKJctMnmY7K6EkaNIy
          aXvWz8mIUdUd1zAnO+6J2TPqPGJB24t/YACI89Apat7qBghDshf+GIVMxvGvddfGx0rw5
          nhjjjytN8TOIiE+QtLMOkfITkVQW0qC6QdqFJzbahpR7hb2VKcnJy1rtt1Dq/PghzPwvB
          7Pl8RP0YUOgtM5lLmW9Rk10VsaOxb7VkdZPZ6kZDBGxt50synGBTubiWMyIwZnj05/caU
          +qg6DBNDfqSd5vTaac3GEX8RdwJnkvcJAigR69IabDouxEf1ADUJR5Y8sa5klM4O/Npyi
          lxtkUq+qMrB0mDprG0GajsTewUHhmQuvK2iXtF6gYhu7nu9ZFB7guxGlZkmEHkG81k3wP
          OLAEv1XdS62d6K2VXKKxkvZtskpkvnBqI1vcQAD6bVyXox0qI0dl7FLrQSgNj0=
      SECRET_KEY: !encrypted/pkcs1-oaep
        - hS96ps41fpUOzIHhYKwbkjRL/McFkr11u/f278+551ERkismUfgJE9rQBVno59+P/h6Q2
          4kvA9uZH2mAWi6OhbXjLFJaDEex24IbWBQsgK+sxhzwVSFcAUXxJMuDRbiBO+/8z92x/y
          VWRN9Bjc1WhHt/ImcRpA8X0hK9cpiybDwVsw/cHsiO+IEUNUxbXLSTzKiTrUNdw1DleQz
          7odARKHP/S2rTNOnk9IVzcvv8TDh/i+sTH1HC3PlD6/UdjVc3lRSx0zOtJDKBllqxLxtO
          RTym4XER+LLXR9Qm+4sU7r9/vgBQfERXxTEHMWYlXnJcRhVqpcXAYxArChfTztuRdiWyL
          qRUV/9m9J2mnkKx/BDxP24Fj9UM4a20b0KTyy5cLQNtSfCqdnxR06CGSpYh7tZkK+HIJR
          8BMB6A6PQG1pP8FDdtzdo/hjuBY6ZuTJKwBdhuZBjUsj4pPyldeVqv4GSFNOhL/iKieHk
          RyKDSBdZyCegwzIoi0o4qNAAH7vHigbwVJuZhg8m3BqyzhAQ3ksaApmH5GuVFNHXDumXs
          9QpZ5jaB/7DDR4OUCqp38zMnhyoI7AKA/DBjAqaxAgI+nyHSsuUy5jq1axbe7x1IJ6nSA
          ylZKNrv6FFF4P3kOIWEE8VYNy+ZEaQZp41QdVTZoNVYEUUAwer/C1zlBgcMCbM=

- semaphore:
    name: semaphore-openstack-octavia-amphora-image-publish
    max: 1

- job:
    name: openstack-octavia-amphora-image-build
    nodeset: ubuntu-jammy-large
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: openstack-octavia-amphora-image-build-zed
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: zed
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-antelope
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-bobcat
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-publish-zed
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: zed
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-antelope
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-bobcat
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - openstack-octavia-amphora-image-build-zed
        - openstack-octavia-amphora-image-build-antelope
        - openstack-octavia-amphora-image-build-bobcat
    post:
      jobs:
        - openstack-octavia-amphora-image-publish-zed:
            branches: main
        - openstack-octavia-amphora-image-publish-antelope:
            branches: main
        - openstack-octavia-amphora-image-publish-bobcat:
            branches: main
