---
- secret:
    name: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
    data:
      ACCESS_KEY: !encrypted/pkcs1-oaep
        - gYDtKcJ0yBqe56w5AMew2JDjnVxpSQwO/YCd3OJcmLpoROoktVY2eGX+PdrkcqvrG+6YK
          mwXekrAEyOSa5syvAc8ijgThM6fL98v5g+sV3PTfGA+HsdrCrL3RrCSstW6XEopzmjN7q
          /6hpbS+BV6QcITkbtV/LM2RtufLsMpVTz9LxnHhCoX5OEnSA6BLsWHJDnxf+FgX+fvpX6
          VxPiOapdKpn+coWBPMtWQcPuM4nG7H4e9CUfs9QYCt6glpiz8bMtOQleYxBgzfRq0aqor
          7XsNaVk18vjgQsO6k6OOt8COw9wR1OE+i9Iptlu4hXREZsEoJAki3LjYMygSaKdtDicQg
          JwwbPqiWPWX2dlYP1NXZHhdjNBZy1LEXgYjIhVFKRF21s35jQF7tYxp4Y60yTdtSBVjDe
          TZfzRdc6ij77ItUw0dz/XBS18x5v+pBKHbQZbbPWMfTpqFXuy1w4BTGdWlrlNqULuUUGN
          pMbn5fP+LfX8NdhmBaWwR4Odj4BiE6afkGi5Sc+6aVj4ALevaCiQsCOM8OWeQjw0YWN/D
          6zHhY56DQeDPrYzAsO8g8xhb9Y5H2Au9bqSO8kG3oTSbMaEJXcP//MxkAC+ytR3DYJbQI
          FKywKmaaTcFQPxE2nhcqxYk+j1XiSeL8YwYe6QITQfDIFmxtZ/UZMojheKxq+k=
      SECRET_KEY: !encrypted/pkcs1-oaep
        - eVU1nYoek4ZTekEIa+2EYrUhroalkz/202XN8CZmStDd3CGkvgnpYNNdqqODVPLqY0DYo
          YENPpelCz1xprKSZnv3p1B8V75vmiWDg0S3cIgNx63vrYFu0hZMvHqnHn5ti6v8BSaoUE
          CIubez/2tqyiPWLb7DQoLetfWvbB4/KS5lCLIejx37jtbtP5dt52snFsgZUXEdCLGEHfK
          2YFWesUUb/hAcBksphlbdttwr2x1CULSybuau2mpw10VtgYXTlCnULH7O279tG91Am8Qx
          qRZXhN6y2u97CBxnA7Q+JmR6b70J1eH+kUmWo0B5dXK4PPY5fQh8HU4UajmDS63OT/yKR
          Eqs30pi7s0YXSi66Hywb/VC8Rh0aTmY2HCRdweOiRSUqD0Kofw3MMYi9yPahyxaAwis1U
          Ezjga8OPFMPKcNMlMvlehqowqhGSK0QATbJc5SXXJ4CicNAi1O9rDJJC1QeuXd7Rpw1l0
          SbK+bfZ2uh1NI9ZGgs2xqNwhSHTNimOUbkPFGEGCOH5J3tg1rtgYNWv2Td9ghAcKlRT5R
          PRL1Mw8bZ3mI+8fPfJkNC+lzIh0VgCj+t2APvFApJdFZWoWtPRExq7f08bc4CQvaCX1Np
          u1NEkQ/h2GeZn64Ra0LqFlCnywVtJBHxtWTgSXhG562G8CUK2v+dHT4E0LPBsY=

- semaphore:
    name: semaphore-openstack-octavia-amphora-image-publish
    max: 1

- job:
    name: openstack-octavia-amphora-image-cleanup
    run: playbooks/cleanup.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-build
    nodeset: ubuntu-jammy-large
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: openstack-octavia-amphora-image-build-2023.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2024.1
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.1"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-build-2024.2
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.2"
      upload_image: false

- job:
    name: openstack-octavia-amphora-image-publish-2023.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2023.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2024.1
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.1"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- job:
    name: openstack-octavia-amphora-image-publish-2024.2
    semaphores:
      - name: semaphore-openstack-octavia-amphora-image-publish
    parent: openstack-octavia-amphora-image-build
    vars:
      version_openstack: "2024.2"
      upload_image: true
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_OCTAVIA_AMPHORA_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - openstack-octavia-amphora-image-build-2023.2
        - openstack-octavia-amphora-image-build-2024.1
        - openstack-octavia-amphora-image-build-2024.2
    periodic-daily:
      jobs:
        - openstack-octavia-amphora-image-cleanup
        - openstack-octavia-amphora-image-publish-2023.2
        - openstack-octavia-amphora-image-publish-2024.1
        - openstack-octavia-amphora-image-publish-2024.2
    post:
      jobs:
        - openstack-octavia-amphora-image-cleanup:
            branches: main
        - openstack-octavia-amphora-image-publish-2023.2:
            branches: main
        - openstack-octavia-amphora-image-publish-2024.1:
            branches: main
        - openstack-octavia-amphora-image-publish-2024.2:
            branches: main
