---
- name: Pre
  hosts: all

  roles:
    - ensure-pip

  vars:
    required_packages:
      - debootstrap
      - kpartx
      - lftp
      - qemu-utils
      - squashfs-tools

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: "{{ required_packages }}"

    - name: Install required python packages
      become: true
      ansible.builtin.pip:
        requirements: "{{ zuul.project.src_dir }}/requirements.txt"
